ip_range:
  start: "192.168.1.1"
  end: "192.168.1.254"

passlist:
  - "192.168.1.10"
  - "192.168.1.20"

whitelist:
  - "10.0.0.1"
  - "172.16.0.1"

retry:
  count: 3
  delay: 5 # seconds

scan_interval:
  normal: 60 # seconds
  after_activation: 300 # seconds

gpio:
  relay_pin: 17

logging:
  level: INFO
  file: "ip_monitor.log"
