# Network Configuration
ip_ranges:
  - start: "192.168.1.1"
    end: "192.168.1.254"
    pin: 17
  - start: "10.0.0.1"
    end: "10.0.0.254"
    pin: 18
  - start: "172.16.0.1"
    end: "172.16.0.254"
    pin: 19
  - start: "192.168.2.1"
    end: "192.168.2.254"
    pin: 20

# Whitelist and Passlist Configuration
whitelist:
  - ip: "8.8.8.8"
    pin: 21
  - ip: "1.1.1.1"
    pin: 22

passlist:
  - "192.168.1.100"
  - "10.0.0.50"

# Ping Configuration
ping:
  timeout: 1  # seconds
  count: 3
  interval: 0.5  # seconds

# Reconnection Configuration
reconnect:
  attempts: 5
  interval: 5  # seconds

# Timing Configuration
cycle_interval:
  normal: 60  # seconds
  alert: 10   # seconds

# Threading Configuration
max_threads: 50