ip_range:
  start: "192.168.2.114"
  end: "192.168.1.115"

whitelist:
  - "192.168.2.121"

passlist:
  - "192.168.2.111"

ping:
  interval: 5 # seconds
  retry:
    count: 3
    delay: 1 # seconds

relay:
  pin: 17

logging:
  level: INFO
  file: "ip_monitor.log"
